services:
    nginx-react:
      container_name: ngixreactapp
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      environment:
        NODE_ENV: production
